[package]
name = "lito-frontend"
version.workspace = true
module = "lito.frontend"

[library]
archive = "lito.frontend"
discovery = "module"

[usage]
private-options = [
  "-fPIC",
  "-Wall",
  "-Wpedantic",
  "-Wno-gnu-statement-expression",
  "-Wno-deprecated-declarations",
  "-Wunknown-attributes",
  "-fsized-deallocation",
]

[dependencies.rstd-std]
workspace = true
visibility = "public"

[dependencies.rstd-nostd]
workspace = true
visibility = "runtime"
