[package]
name = "lito-frontend"
version.workspace = true

[lib]
name = "lito-frontend"
module = "lito.frontend"
archive = "lito.frontend"

[dependencies]
rstd-std = { workspace = true, pub = true }
rstd-nostd = { workspace = true, usage = "link" }
