[package]
name = "lito-frontend"
version.workspace = true

[lib]
name = "lito-frontend"
module = "lito.frontend"
archive = "lito.frontend"
discovery = "module"

[usage]
private-options = [
  "-fsized-deallocation",
]

[dependencies.rstd-std]
workspace = true
visibility = "public"

[dependencies.rstd-nostd]
workspace = true
visibility = "runtime"
