[workspace]
name = "lito"
members = ["frontend", "core", "cli", "test"]
default-members = ["cli", "test"]

[workspace.package]
version = "0.1.0"

[workspace.dependencies.lito-frontend]
path = "frontend"

[workspace.dependencies.lito-core]
path = "core"

[workspace.dependencies.rstd-std]
git = "https://github.com/litocpp/rstd.git"

[workspace.dependencies.rstd-nostd]
git = "https://github.com/litocpp/rstd.git"

[workspace.dependencies.rstd-json]
git = "https://github.com/litocpp/rstd.git"

[workspace.dependencies.rstd-bench]
git = "https://github.com/litocpp/rstd.git"

[workspace.dependencies.rstd-toml]
git = "https://github.com/litocpp/rstd.git"

[workspace.dependencies.rstd-argparse]
git = "https://github.com/litocpp/rstd.git"

[workspace.dependencies.rstd-test]
git = "https://github.com/litocpp/rstd.git"

[profile]
exceptions = false
rtti = false

[profile.perf]
inherits = "release"
opt-level = 2
debug = "line-tables-only"
strip = "none"
lto = "off"
