[workspace]
name = "lito"
members = ["frontend", "core", "c", "cpp", "toolchain", "driver", "cli", "tests"]
default-members = ["cli"]

[workspace.package]
version = "0.2.1"
license = "MIT OR Apache-2.0"

[workspace.dependencies.lito-frontend]
path = "frontend"

[workspace.dependencies.lito-core]
path = "core"

[workspace.dependencies.lito-c]
path = "c"

[workspace.dependencies.lito-cpp]
path = "cpp"

[workspace.dependencies.lito-toolchain]
path = "toolchain"

[workspace.dependencies.lito-driver]
path = "driver"

[workspace.dependencies.luato]
git = "https://github.com/litocpp/luato.git"

[workspace.dependencies.rstd-std]
git = "https://github.com/litocpp/rstd.git"

[workspace.dependencies.rstd-nostd]
git = "https://github.com/litocpp/rstd.git"

[workspace.dependencies.rstd-json]
git = "https://github.com/litocpp/rstd.git"

[workspace.dependencies.rstd-bench]
git = "https://github.com/litocpp/rstd.git"

[workspace.dependencies.rstd-toml]
git = "https://github.com/litocpp/rstd.git"

[workspace.dependencies.rstd-argparse]
git = "https://github.com/litocpp/rstd.git"

[workspace.dependencies.rstd-test]
git = "https://github.com/litocpp/rstd.git"

[profile]
exceptions = false
rtti = false

[profile.perf]
inherits = "release"
opt-level = 2
debug = "line-tables-only"
strip = "none"
lto = "off"
