[workspace]
name = "lito"
members = ["third-party/zstd", "frontend", "core", "pack", "cpp", "tools", "toolchain", "driver", "cli"]
default-members = ["cli"]

[workspace.package]
version = "0.8.0"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
lito-frontend = { path = "frontend" }
lito-core = { path = "core" }
lito-pack = { path = "pack" }
lito-cpp = { path = "cpp" }
lito-tools = { path = "tools" }
lito-toolchain = { path = "toolchain" }
lito-driver = { path = "driver" }
lito-zstd = { path = "third-party/zstd" }
licrypto = "0.1.0"
rstd-std = "0.1.1"
rstd-nostd = "0.1.1"
rstd-json = "0.1.1"
rstd-serde = "0.1.1"
rstd-bench = "0.1.1"
rstd-toml = "0.1.1"
rstd-argparse = "0.1.1"
rstd-test = "0.1.1"
luato = { git = "https://github.com/litocpp/luato.git" }

[workspace.external-sources.zstd]
git = "https://github.com/facebook/zstd.git"
rev = "f8745da6ff1ad1e7bab384bd1f9d742439278e99"

[profile.base]
exceptions = false
rtti = false

[profile.perf]
inherits = "release"
opt-level = 2
debug = "line-tables-only"
strip = "none"
lto = "off"
