[package]
name = "lito-utf8proc"
version = "2.10.0"
standard = "c99"
license = "MIT"

[external-sources.utf8proc]
archive = "https://github.com/JuliaStrings/utf8proc/archive/refs/tags/v2.10.0.tar.gz"
sha256 = "6f4f1b639daa6dca9f80bc5db1233e9cbaa31a67790887106160b33ef743f136"

[source-groups.runtime]
external-source = "utf8proc"
sources = ["utf8proc.c"]

[lib]
name = "lito-utf8proc"
archive = "lito.utf8proc"
source-groups = ["runtime"]

[usage]
public-include-directories = [
  { external-source = "utf8proc", path = "." },
]
public-definitions = ["UTF8PROC_STATIC"]
