[package]
name = "demo-workspace-common"
version.workspace = true

[lib]
name = "demo-workspace-common"
module = "demo.workspace.common"
archive = "common"
discovery = "explicit"
sources = ["common.cppm"]
