[package]
name = "demo-workspace-app_two"
version.workspace = true

[[bin]]
name = "demo-app"
sources = ["main.cpp"]

[dependencies]
demo-workspace-common = { path = "../common", visibility = "private" }
