[package]
name = "lito-cpp"
version.workspace = true

[lib]
name = "lito-cpp"
module = "lito.cpp"
archive = "lito.cpp"

[dependencies]
lito-core = { workspace = true, visibility = "public" }
lito-frontend = { workspace = true, visibility = "public" }
rstd-std = { workspace = true, visibility = "public" }
rstd-nostd = { workspace = true, visibility = "link" }
