[package]
name = "demo-base"
version = "0.1.0"

[lib]
name = "demo-base"
module = "demo.base"
archive = "demo.base"
sources = [
  "src/lib.cppm",
  "src/detail.cppm",
  "src/lib.cpp",
]

[usage]
public-include-directories = []
private-include-directories = []
public-definitions = []
private-definitions = []
options = []
