[package]
name = "lito"
version.workspace = true

[[bin]]
module = "lito.executable"
name = "lito"
discovery = "module"
link-stdlib = false

[dependencies.lito-core]
workspace = true
visibility = "private"

[dependencies.rstd-std]
workspace = true
visibility = "private"

[dependencies.rstd-argparse]
workspace = true
visibility = "private"

[dependencies.rstd-nostd]
workspace = true
visibility = "link"
