[package]
name = "lito"
version.workspace = true

[[bin]]
module = "lito.executable"
name = "lito"
link-stdlib = false

[dependencies.lito-driver]
workspace = true
visibility = "private"

[dependencies.lito-pack]
workspace = true
visibility = "private"

[dependencies.rstd-std]
workspace = true
visibility = "private"

[dependencies.rstd-argparse]
workspace = true
visibility = "private"

[dependencies.rstd-nostd]
workspace = true
visibility = "link"

[external-sources.builtin-pmacro]
path = "../plugins/pmacro"

[external-sources.builtin-qt]
path = "../data/script-packages/qt"

[external-sources.builtin-libxml2]
path = "../data/sdk/libxml2/2.13.8-minimal-elf-v1"
