[package]
name = "lito-core"
version.workspace = true

[lib]
name = "lito-core"
module = "lito.core"
archive = "lito.core"

[dependencies]
rstd-std = { workspace = true, visibility = "public" }
rstd-json = { workspace = true, visibility = "private" }
rstd-serde = { workspace = true, visibility = "private" }
rstd-toml = { workspace = true, visibility = "private" }
rstd-nostd = { workspace = true, visibility = "link" }
licrypto = { workspace = true, visibility = "public" }
