[package]
name = "lito-core"
version.workspace = true

[lib]
name = "lito-core"
module = "lito.core"
archive = "lito.core"

[dependencies]
rstd-std = { workspace = true, pub = true }
rstd-json = { workspace = true }
rstd-serde = { workspace = true }
rstd-toml = { workspace = true }
rstd-nostd = { workspace = true, usage = "link" }
licrypto = { workspace = true, pub = true }
