[package]
name = "lito-core"
version.workspace = true

[lib]
name = "lito-core"
module = "lito.core"
archive = "lito.core"

[dependencies.rstd-std]
workspace = true
visibility = "public"

[dependencies.rstd-json]
workspace = true
visibility = "private"

[dependencies.rstd-toml]
workspace = true
visibility = "private"

[dependencies.rstd-nostd]
workspace = true
visibility = "link"

[dependencies.lito-utf8proc]
workspace = true
visibility = "private"

[external-dependencies.pkg-config.libsodium]
module = "libsodium"
visibility = "link"
