[package]
name = "lito-archive"
version.workspace = true

[lib]
name = "lito-archive"
module = "lito.archive"
archive = "lito.archive"

[dependencies.lito-zstd]
workspace = true
visibility = "private"

[dependencies.rstd-std]
workspace = true
visibility = "public"

[dependencies.rstd-nostd]
workspace = true
visibility = "link"
