#include <rstd/test/gtest.hpp>

import rstd;
import rstd.test;
import lito.system;
import lito.tools;
import lito.tools.cargo;
import lito.test.support;

using namespace rstd::prelude;
using namespace rstd::literals;
using namespace lito::system;
using namespace lito_test;
using PathBuf = rstd::path::PathBuf;

class CargoProvider : public ProjectFixture {};

TEST(CargoProviderProtocol, NativeLinkTokensPreserveOrderAndRejectCommandInjection) {
    auto unix =
        lito::tools::cargo::parse_native_arguments("native-static-libs: -ldl -lpthread -ldl"_str);
    ASSERT_TRUE(unix.is_ok());
    ASSERT_EQ(unix->len(), usize(3));
    EXPECT_EQ((*unix)[usize {}].as_str(), "-ldl"_str);
    EXPECT_EQ((*unix)[usize(1)].as_str(), "-lpthread"_str);
    EXPECT_EQ((*unix)[usize(2)].as_str(), "-ldl"_str);

    auto macos = lito::tools::cargo::parse_native_arguments(
        "native-static-libs: -framework Security -lSystem"_str);
    ASSERT_TRUE(macos.is_ok());
    ASSERT_EQ(macos->len(), usize(3));

    auto msvc = lito::tools::cargo::parse_native_arguments(
        "native-static-libs: ws2_32.lib userenv.lib"_str);
    ASSERT_TRUE(msvc.is_ok());
    ASSERT_EQ(msvc->len(), usize(2));

    EXPECT_TRUE(lito::tools::cargo::parse_native_arguments("native-static-libs: @response.rsp"_str)
                    .is_err());
    EXPECT_TRUE(
        lito::tools::cargo::parse_native_arguments("native-static-libs: -Wl,--whole-archive"_str)
            .is_err());
    EXPECT_TRUE(
        lito::tools::cargo::parse_native_arguments("native-static-libs: relative/libnative.a"_str)
            .is_err());
}

TEST_F(CargoProvider, CargoBuildReturnsExactStaticlibAndOrderedNativeClosure) {
    constexpr ProjectFile files[] = {
        { "Cargo.toml"_str, R"toml([package]
name = "lito-cargo-provider-fixture"
version = "0.1.0"
edition = "2024"

[lib]
name = "lito_cargo_provider_fixture"

[features]
default = ["default-answer"]
default-answer = []
selected = []
)toml"_str },
        { "Cargo.lock"_str, R"lock(# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "lito-cargo-provider-fixture"
version = "0.1.0"
)lock"_str },
        { "src/lib.rs"_str, R"rust(#[unsafe(no_mangle)]
pub extern "C" fn lito_cargo_provider_answer(value: i32) -> i32 {
    value + 1
}
)rust"_str },
    };
    auto project = materialize("cargo-provider"_str, files);
    ASSERT_TRUE(project.is_ok());
    auto environment = ResolvedProcessEnvironment::resolve(ProcessEnvironmentSpec {});
    ASSERT_TRUE(environment.is_ok());
    auto resolver = lito::tools::ToolResolver(*environment);
    auto resolved = resolver.require(
        lito::tools::Tool::Cargo,
        lito::tools::command_tool_requirement(lito::tools::HostToolCapability::CargoBuild,
                                              "Cargo provider test"_str));
    ASSERT_TRUE(resolved.is_ok());
    auto provider = lito::tools::cargo::identify_provider(rstd::move(resolved).unwrap().executable,
                                                          *environment);
    ASSERT_TRUE(provider.is_ok());
    EXPECT_FALSE(provider->identity.is_empty());
    EXPECT_FALSE(provider->host_target.is_empty());

    auto manifest = project->root.join(PathBuf::from("Cargo.toml"_str).as_path());
    auto metadata = lito::tools::cargo::query_metadata(
        *provider,
        lito::tools::cargo::MetadataRequest {
            .source_root = project->root.clone(),
            .manifest    = manifest.clone(),
            .package     = String::make("lito-cargo-provider-fixture"_str),
        },
        *environment);
    ASSERT_TRUE(metadata.is_ok());
    EXPECT_EQ(metadata->name.as_str(), "lito-cargo-provider-fixture"_str);
    EXPECT_EQ(metadata->target_name.as_str(), "lito_cargo_provider_fixture"_str);
    EXPECT_EQ(metadata->workspace_root.as_path(), project->root.as_path());

    auto work    = build_root("cargo-provider"_str);
    auto target  = work.join(PathBuf::from("target"_str).as_path());
    auto request = lito::tools::cargo::BuildRequest {
        .alias            = String::make("fixture"_str),
        .source_root      = project->root.clone(),
        .manifest         = metadata->manifest.clone(),
        .package          = String::make("lito-cargo-provider-fixture"_str),
        .features         = strings("selected"_str),
        .default_features = false,
        .profile          = String::make("dev"_str),
        .target           = provider->host_target.clone(),
#if RSTD_OS_WINDOWS
        .archive_suffix = String::make(".lib"_str),
#else
        .archive_suffix = String::make(".a"_str),
#endif
        .request_identity = String::make("cargo-provider-request-v1"_str),
        .work_root        = work.clone(),
        .target_directory = target.clone(),
        .jobs             = usize(1),
    };
    auto built =
        lito::tools::cargo::build_static_library(*provider, *metadata, request, *environment);
    ASSERT_TRUE(built.is_ok());
    EXPECT_TRUE(built->archive.as_path().starts_with(target.as_path()));
    EXPECT_FALSE(built->archive_digest.is_empty());
    EXPECT_TRUE(built->archive_size > u64 {});
    EXPECT_FALSE(built->native_link_arguments.is_empty());

    auto repeated =
        lito::tools::cargo::build_static_library(*provider, *metadata, request, *environment);
    ASSERT_TRUE(repeated.is_ok());
    EXPECT_EQ(repeated->identity.as_str(), built->identity.as_str());
    EXPECT_EQ(repeated->archive.as_path(), built->archive.as_path());
    EXPECT_TRUE(repeated->fresh);
}
