[package]
name = "lito-sodium"
version.workspace = true
standard = "c17"
license = "ISC AND BSD-2-Clause AND (MIT OR Apache-2.0)"

[external-sources.libsodium]
workspace = true

[source-groups.runtime]
external-source = "libsodium"
sources = [
  "src/libsodium/crypto_hash/sha256/cp/hash_sha256_cp.c",
  "src/libsodium/crypto_verify/verify.c",
]

[source-groups.support]
sources = ["support.c"]

[lib]
name = "lito-sodium"
archive = "lito.sodium"
source-groups = ["runtime", "support"]

[usage]
public-include-directories = [{ external-source = "libsodium", path = "src/libsodium/include" }]
private-include-directories = [
  { external-source = "libsodium", path = "src/libsodium" },
  { external-source = "libsodium", path = "src/libsodium/include/sodium" },
]
public-definitions = ["SODIUM_STATIC"]
private-definitions = ["CONFIGURED=1", "HAVE_GCC_MEMORY_FENCES=1"]
