[package]
name = "lito-driver"
version.workspace = true

[lib]
name = "lito-driver"
module = "lito.driver"
archive = "lito.driver"

[dependencies]
lito-core = { workspace = true, pub = true }
lito-pack = { workspace = true, pub = true }
lito-cpp = { workspace = true, pub = true }
lito-tools = { workspace = true, pub = true }
lito-toolchain = { workspace = true, pub = true }
lito-frontend = { workspace = true, pub = true }
luato = { workspace = true }
rstd-std = { workspace = true, pub = true }
rstd-json = { workspace = true }
rstd-serde = { workspace = true }
rstd-toml = { workspace = true }
rstd-bench = { workspace = true }
rstd-nostd = { workspace = true, usage = "link" }
