export module lito.core:manifest;

export import :manifest.profile;
export import :manifest.conditional;
export import :manifest.source_convention;
export import :manifest.language;
export import :manifest.target;
export import :manifest.dependency;
export import :manifest.build_tool;
export import :manifest.build_script;
export import :manifest.package;
export import :manifest.workspace;
export import :manifest.document;
export import :manifest.edit;
export import :manifest.initialize;
export import :manifest.standalone;
export import :manifest.publish;
export import :manifest.error;
export import :manifest.locator;
