[package]
name = "lito-tools"
version.workspace = true

[lib]
name = "lito-tools"
module = "lito.tools"
archive = "lito.tools"

[dependencies]
lito-core = { workspace = true, pub = true }
rstd-std = { workspace = true, pub = true }
rstd-json = { workspace = true, pub = true }
rstd-toml = { workspace = true, pub = true }
rstd-nostd = { workspace = true, usage = "link" }
