[package]
name = "demo-workspace-unused"
version.workspace = true

[lib]
name = "demo-workspace-unused"
module = "demo.workspace.unused"
archive = "common"
discovery = "explicit"
sources = ["unused.cppm"]
