[package]
name = "demo-app"
version = "0.1.0"

[lib]
name = "demo-app"
module = "demo.app"
archive = "demo.app"
discovery = "module"

[dependencies.demo-base]
path = "../demo-base"
visibility = "public"
