#!/bin/sh

count_file="$PKG_CONFIG_SYSROOT_DIR/provider-count"
count=0
if [ -f "$count_file" ]; then
  read -r count < "$count_file"
fi
count=$((count + 1))
printf '%s\n' "$count" > "$count_file"

for argument in "$@"; do
  case "$argument" in
    --version)
      printf '%s\n' 'fixture-provider-1'
      exit 0
      ;;
    --modversion)
      query=modversion
      ;;
    --cflags)
      query=cflags
      ;;
    --libs)
      query=libs
      ;;
  esac
done

case "$query" in
  modversion)
    printf '%s\n' '1.0.0'
    ;;
  cflags)
    printf '%s\n' '-DLITO_COUNTING_PROVIDER=1'
    ;;
  libs)
    printf '%s\n' '-llito_counting_provider'
    ;;
  *)
    printf '%s\n' 'unsupported query' >&2
    exit 2
    ;;
esac
