[package]
name = "demo-app"
version = "0.1.0"

[lib]
name = "demo-app"
module = "demo.app"
archive = "demo.app"
discovery = "explicit"
sources = [
  "src/lib.cppm",
  "src/lib.cpp",
]

[dependencies.demo-base]
path = "../demo-base"
visibility = "public"
